<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Version>2.0.0</Version>
    <ApplicationIcon>app_icon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="app_icon.ico" />
    <EmbeddedResource Include="Themes\DarkXML.xshd" />
    <EmbeddedResource Include="Themes\DarkJSON.xshd" />
    <EmbeddedResource Include="Themes\LightXML.xshd" />
    <EmbeddedResource Include="Themes\LightJSON.xshd" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Management" Version="10.0.11" />
    <PackageReference Include="Titanium.Web.Proxy" Version="5.10.0" />
  </ItemGroup>

</Project>
